GET http://localhost:3001/api/test HTTP/1.1

###

POST http://localhost:3001/api/services/ HTTP/1.1
content-type: application/json

{
    "tagName" : "tagName", 
    "serviceTime": 13.2
}


###
POST http://localhost:3001/api/addTicket HTTP/1.1
Content-type: application/json

{ "service" : "non esiste"}

###

POST http://localhost:3001/api/ticket 
content-type: application/json

{
    "ticket_num" : 5, 
    "id_service" : "AS",
    "start_time" : 5, 
    "end_time" : 5, 
    "id_officer" : 5, 
    "date" : "2021-10-15" 
}

###

GET http://localhost:3001/api/services HTTP/1.1

###

GET http://localhost:3001/api/Customer HTTP/1.1

###

GET http://localhost:3001/api/NextServeCustomer HTTP/1.1

###

GET http://localhost:3001/api/ServedCustomer HTTP/1.1

###
PUT http://localhost:3001/api/updateTickets/officer/1 HTTP/1.1